### ISSUE TITLE
Make page notes ignore hash section in urls

### ISSUE THREAD

**Issue by foxt451** [Sav22999/websites-notes#10]
When I read docs, there is usually a navigation panel on the side where you can jump to different sections of the page. I think it still is the same page, but the notes disappear and are scoped to different sections, because the url technically changes (hashtag is added). It would be convenient to have the notes remain

**Comment by Sav22999** [comment]
True, thanks.
I'll update asap

**Comment by foxt451** [comment]
@Sav22999 Thanks! Also, I've noticed that the icon changes from green (has notes) to orange (no notes) when switching sections, even though that setting is on and you can see the note when clicking on addon icon. Not sure if this is by design

**Comment by Sav22999** [comment]
@foxt451 it's another bug, thanks!
I'm releasing the 2.2.2 version, which fix this bug

😄
