### ISSUE TITLE
Add a Darker Theme or a Dark Mode

### ISSUE THREAD

**Issue by EnriqueTMT** [Sav22999/websites-notes#105]
I want to begin with some gratitude. You've created a browser extension that works on both Chrome and Firefox. This is also the first browser notepad browser extension to be open source. It's a great addition to the open-source ecosystem, encouraging transparency and community-driven innovation.

# Problem(s)
- The current white and orange theme is pretty bright.
- The orange accent doesn't match most system or browser themes and makes the notepad out of place.

# Solution(s)
Below are some possible options that might address the problems listed above. This isn't a request for all the following. Just one of them would do.
- Add a dark mode.
- Add an option to change the orange colors to a more neutral color like gray.
- Add the option to change the primary and secondary colors to a custom color or to a set of predefined color options.

# Alternatives
I don't know of any open source alternatives, but I used to use Eloquent as an alternative. It may spark some inspiration for some other features (not referring to the AI features that they've added).
Eloquent Browser Extension Link: https://chromewebstore.google.com/detail/eloquent-quick-capture-an/olkmpnafmgcfindlljhgnminkhkfcckl

**Comment by Sav22999** [comment]
@EnriqueTMT Hi, thank you very much for all your feedbacks.

It's already available a "dark" theme, but it doesn't exist a "monochrome dark" theme. I'll add more theme in future 😊

Although it's available in Firefox and Chrome, the Firefox version is the most updated release (some technical issues either Chrome)

**Comment by Sav22999** [comment]
@EnriqueTMT In the 4.1 release you can find two new themes ("darker" and "lighter") ☺️

**Comment by EnriqueTMT** [comment]
@Sav22999 Has a monochrome theme moved up in the to-do list? Or maybe the ability to change the color orange?

**Comment by Sav22999** [comment]
@EnriqueTMT The monochrome theme is already present. It's called "Darker" or "Lighter" 

Don't you find it in Settings? 🤔

**Comment by Sav22999** [comment]
@EnriqueTMT You're using an old version of Notefox. Do you use Firefox or Chrome based browser ?

**Comment by EnriqueTMT** [comment]
@Sav22999 
Chrome (Vivaldi). 
I thought I had checked the chrome page for updates. It should have been automatic though. I'm assuming the Chrome version is a little behind?

**Comment by Sav22999** [comment]
@EnriqueTMT Yes, unfortunately Chrome version is behind (I'm meeting some issues with the Chrome edition).

It will arrive but I don't know when, sorry

The new Notefox version has many new features https://www.notefox.eu/help/notefox-4.0/ and it will be my care release it asap

**Comment by EnriqueTMT** [comment]
@Sav22999 
I just got a look at the 4.0v. It's too bad but don't worry about the timetable. Thanks for getting back to me and your hard work!
Edit: I just saw you add a screenshot haha.

**Comment by Sav22999** [comment]
@EnriqueTMT I'll work strongly to make the new Chrome edition as well 😄

**Comment by Sav22999** [comment]
@EnriqueTMT New version published also on Chrome and Edge 😊

Let me know

**Comment by EnriqueTMT** [comment]
@Sav22999 Had to reinstall the plugin. How weird. It didn't want to automatically update. Maybe something the Brave browser was doing in the background? It worked out in the end. Nice work!

**Comment by Sav22999** [comment]
@Sav22999 Very weird 🤔 
Anyway, the important is you have the new Notefox and you like it 🥰 

For any other issues, please contact me on Telegram or open another issue
