### ISSUE TITLE
Does notefox try to contact internet while active? (aside from sync function)

### ISSUE THREAD

**Issue by kuolemaaa** [Sav22999/websites-notes#106]

**Comment by Sav22999** [comment]
Absolutely not.

Notefox sync your data (which is totally encrypted) only if you login with a Notefox Account, otherwise it won't contact Internet at all 🙂

Please, tell me if this answered to your question, so I can close this Issue as resolved ☺️

**Comment by kuolemaaa** [comment]
Fair enough, if you are telling the truth, please, advertise it on the project README and the firefox addon page. It is worth mentioning. You can close it if you want

**Comment by Sav22999** [comment]
@kuolemaaa You can find on Terms and on Privacy:

https://www.notefox.eu/terms/
https://www.notefox.eu/privacy/
