### ISSUE TITLE
Add release notes to AMO

### ISSUE THREAD

**Issue by bege10** [Sav22999/websites-notes#110]
Hello,
I am still impressed by your work on this add-on.
I use the add-on "Changelogger" that shows updates of add-ons and the release notes from AMO.
Please, add release notes of Notefox to AMO. Currently one must go to Github to see what has changed.
Thank you very much.

**Comment by Sav22999** [comment]
@bege10 Hi, probably it's a bug of Firefox Add-ons, but when I publish new releases, the textarea where you can insert change-logs is disabled.

I'll see if it's possible insert release notes after the publication

**Comment by bege10** [comment]
> @bege10 Hi, probably it's a bug of Firefox Add-ons, but when I publish new releases, the textarea where you can insert change-logs is disabled.
> 
> I'll see if it's possible insert release notes after the publication

Thank you! I don't think it is an AMO bug because most updates of the add-ons I use contain release notes.

**Comment by Sav22999** [comment]
@bege10 Probably add-on that you use don't have the Firefox addon page in multiple languages.... I don't know.
I'll investigate anyway. Thanks for the reporting ☺️

**Comment by Sav22999** [comment]
@bege10 I've added the release notes since the 1.0 (the first release) 😃

**Comment by bege10** [comment]
> @bege10 I've added the release notes since the 1.0 (the first release) 😃

You are unbeatable! 😄

**Comment by bege10** [comment]
@Sav22999 The release notes have vanished again. 🥴

**Comment by Sav22999** [comment]
@bege10 My fault, sorry. I've forgot to insert manually the release notes here in Github. Fixed, sorry
