### ISSUE TITLE
Sticky note is not showing on Firefox Android

### ISSUE THREAD

**Issue by 9jS2PL5T** [Sav22999/websites-notes#111]
Hi, i noticed, that the pop up is not showing on the Android Version of firefox. For me this is the best feature, because i want to get notified of things i made a note to that linked website. Please review that.

**Comment by Sav22999** [comment]
@9jS2PL5T it should work, I'll investigate in the next days.
Thanks for the report 😊

**Comment by Sav22999** [comment]
@9jS2PL5T I'm checking also this issue but I don't get the same problem. I can write correctly on the popup, and it works in "page", "domain" and "global" too 🤔 

I need more information, please

**Comment by 9jS2PL5T** [comment]
Maybe it is a misunderstanding. On Firefox Windows i can create a popup/overlay note. I do like to see the note as an overlay on that website, because it reminds me of my notes. I don't take a look in the notefox addon that often. Is that overlay also available on notefox android or only on Windows?

**Comment by Sav22999** [comment]
Oh, ok, I guess you mean the "sticky-note" feature, don't you?

https://www.notefox.eu/sticky-notes/

In that case, at the moment, it's not available on Android, I'm sorry 😞
