### ISSUE TITLE
Stuck in settings

### ISSUE THREAD

**Issue by 9jS2PL5T** [Sav22999/websites-notes#113]
When i move to settings on Notefox Android, i'm stuck there. When clicking on all notes, help, translate or website, nothing is happening. I have to reopen the addon site again to navigate.

**Comment by Sav22999** [comment]
@9jS2PL5T Hi, I'm sorry for the late answer –I am in holidays in this period– and for the inconvenience 😢

I'll check this issues asap, thanks for the reporting 😊

**Comment by Sav22999** [comment]
@9jS2PL5T Hi, I don't have this issue. Please, can you tell me more details?

**Comment by 9jS2PL5T** [comment]
I'm happy to check the result :) Thank you.

**Comment by 9jS2PL5T** [comment]
Looks like it is working fine for me now👍🏼
