### ISSUE TITLE
[Feature Request] Ability to add images or screenshots from the clipboard

### ISSUE THREAD

**Issue by Terkyz** [Sav22999/websites-notes#17]
Vivaldi has a great feature that allows to attach clipboard screenshots or own images to the notes, would it be possible to add something like this in this extension? It has its utilities, in my case to save visual reminders of some tutorials on Youtube.

I also think it can be useful to note prices of some products on some websites, which have the habit of deleting the product and not updating the price.

**Comment by Sav22999** [comment]
@Terkyz mh, I need to see this, but I think it's very hard

**Comment by Sav22999** [comment]
I'm implementing this feature. You can find it (as beta) in 3.7
