### ISSUE TITLE
[Feature Request] Ability to rename or name notes

### ISSUE THREAD

**Issue by Terkyz** [Sav22999/websites-notes#18]
Instead of having the domain link of the note page as the title, it would be great to be able to rename it, maybe have the domain link, and the site specific link being able to rename it.

**Comment by Sav22999** [comment]
@Terkyz this it's a great suggestion. I add this to the to-do list 😉

**Comment by Sav22999** [comment]
@Terkyz In the new release (3.4.1) I've added the "title" parameter. For now, it's not editable (it's only the "title of the page"), but in the future probably it will be 😄
