### ISSUE TITLE
[Feature Request] Ability to save notes for url patterns

### ISSUE THREAD

**Issue by milkysupra** [Sav22999/websites-notes#19]
Hello.
Please add ability to create patterns instead of full page address.

Why:
I do love your extention, but for some sites (like youtube) I need to enable parametes as part of the url page to diff between pages with different video

```
https://www.youtube.com/watch?v=<VIDEO_1>
https://www.youtube.com/watch?v=<VIDEO_2>
```

But for some anoter sites I need to disable parameters, because often these parameters change dynamically:
```

https://<WEBSITE>/search/flowers/150?OfferType=VipPlus
https://<WEBSITE>/search/flowers/150?OfferType=Basic
```

and I really dissapointed with that point.

What if there will be ability to use usermasks for webpages instead of full pagename as a feature?

```
https://somesite.org/search/flowers/
https://www.youtube.com/watch?v=id
flowers
http://
watch?v=someid
```

And as I know there's no alternative extentions with the feature for Firefox at all.

**Comment by Sav22999** [comment]
I think this is too specific and not useful for all users. For now, I close this issue
