### ISSUE TITLE
Help with onboarding

### ISSUE THREAD

**Issue by davehunt** [Sav22999/websites-notes#20]
I've installed the extension, but can't see any way to create a note. There's nothing in the toolbar or context menu. What am I missing?

Name: Firefox
Version: 116.0a1
Build ID: 20230608092730
Distribution ID:
Update Channel: nightly
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
OS: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar 6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
Rosetta Translated: false
Multiprocess Windows: 5/5
Fission Windows: 5/5 Enabled by default
Remote Processes: [38](https://github.com/Sav22999/websites-notes/issues/new#remote-processes)
Enterprise Policies: Inactive
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false
Memory Size (RAM): 16.0 GB
Disk Space Available: 64.0 GB

**Comment by Sav22999** [comment]
@davehunt have you checked in the "Extensions" panel?

<img width="385" alt="image" src="https://github.com/Sav22999/websites-notes/assets/32335378/33981cfe-143d-496b-9ae3-8c25615dca2f">

**Comment by davehunt** [comment]
Excellent, thank you. I'm not sure how I missed that!
