### ISSUE TITLE
Feature request: Add notes not related to an URL

### ISSUE THREAD

**Issue by bege10** [Sav22999/websites-notes#27]
This is a very nice add-on, thank you! Additionally to notes that are related to a domain or page I miss a feature to add general notes that are not related to an URL.

**Comment by Sav22999** [comment]
This is an interesting feature. I add this to the to-do list. Thanks!

Have you updated the addon to the latest version (3.3)? Sticky-notes and sync now work?

**Comment by bege10** [comment]
I am glad to hear that you add this feature to the to-do list. Yes, I updated to v3.3 and it works well but I don't use the syching feature. So I don't know whether it works. What do you mean with "sticky notes"?

**Comment by Sav22999** [comment]
You can fix the note to your website now
![telegram-cloud-photo-size-4-5958653102246707093-x](https://github.com/Sav22999/websites-notes/assets/32335378/1863b2de-ec75-4e5e-a9c4-c8c5319206e7)


I described very well here: https://t.me/sav_projects/7/140

**Comment by bege10** [comment]
That looks gorgeous. I will test it the next time I am at my computer. I write from my phone right now.

**Comment by bege10** [comment]
> Have you updated the addon to the latest version (3.3)? Sticky-notes and sync now work?

The sticky notes feature is really amazing! Thank you very much. 👍
