### ISSUE TITLE
change icon aspect whether there are any notes on current website/domain

### ISSUE THREAD

**Issue by frasty** [Sav22999/websites-notes#3]
Hi,
would it be possible to change the notefox icon if the active tab is on a website where a note is already taken? For example a checkmark drawn over the upper right angle of the icon or something like that would give an instant and useful feedback, imho.
Thank you for the good work!

**Comment by Sav22999** [comment]
Hi, it's already in this way. When the icon is green is means there exists a note, otherwise it's orange.

Don't you see this?

**Comment by frasty** [comment]
Oh man, didn't noticed it. Maybe I expected something more prominent, presumably because I am using a dark theme. Thank you anyway!
