### ISSUE TITLE
Notefox 3.4+ and Gloal notes for non-http(s) pages

### ISSUE THREAD

**Issue by Cade66** [Sav22999/websites-notes#39]
Hello @Sav22999, hello everyone,

All versions of Notefox handle all pages, even non-http(s) ones : most appreciated.
Before Notefox 3.4, non-http(s) pages were saved with the 'Domain' tag.
Starting Notefox 3.4, non-http(s) pages are saved with the 'Global' tag.

By non-http(s) pages I have in mind:
Firefox abouts, of the form about:[xyz]
Firefox extensions, of the form moz-extension://[DATA]

Problem-1 : Notes saved from non-http(s) pages under Notefox 3.3+ are not displayed when opened with Notefox 3.4+, though the Notefox toolbar button indicates that the note is available. Not a real problem: in 'All notes' we copy the note, delete it, and create a new note. This new note, of a non-http(s) page, will now be saved as a 'Global' note and all is fixed.

Problem-2 is more bothering : new notes for non-http(s) pages, because saved as 'Global' appear on every visited page given this is the very purpose of 'Global' notes.
This is bothering for notes which are meant to handle a specific non-http(s) page. In particular, personally, I have notes for several Firefox abouts (i.e. about:config) as well as for several Firefox extensions (i.e. moz-extension://[UUID]/dashboard.html#settings.html

Wish/suggestion, if feasible of course, is to handle non-http(s) pages' notes as 'Domains' (as with previous verions of Notefox) rather than as 'Global'.
The ideal would be a new category such as 'Other' besides 'Global', 'Domain' and 'Page' which would handle all non-http(s) pages, but this is perhaps an excessive wish given that managing such pages with the 'Domain' tag works fine.

That's it :)

**Comment by Cade66** [comment]
@Sav22999 , great!
Thanks for your quick as always reply :)

**Comment by Sav22999** [comment]
@Cade66 I've just published a new release 3.4.1 where I've fixed this bug. Thanks for your report

(I've added also another feature, but it's not important for you 😄 )

**Comment by Cade66** [comment]
Just installed Notefox 3.4.1.1, tested thoroughly , runs flawlessly, the "issue" is indeed fixed, most appreciated.
@Sav22999, thanks for your work. Notefox is a constant Firefox companion here, so helpful need to say.
