### ISSUE TITLE
All notes page empty

### ISSUE THREAD

**Issue by bege10** [Sav22999/websites-notes#58]
Notefox v3.7.3 all notes page is empty although the respective notes are displayed in the popup.
Additionally the buttons on the all notes page have not function.

**Comment by Sav22999** [comment]
@bege10 hi, can you describe step-by-step with some screenshots as well please?

I'm sorry for the inconvenience

**Comment by bege10** [comment]
1. Open popup and see related note
2. Click on "all notes"
3. All notes page only shows as screenshot below
4. Click on any button - no reaction - except sorting, I did not test "clear all notes" ;)

![Screenshot_342](https://github.com/Sav22999/websites-notes/assets/1184237/106045f9-4efe-4f24-9964-46e83358bfb7)

**Comment by Sav22999** [comment]
@bege10 this shouldn't be the correct behaviour. Some other information needed:
- If you press on "Export" can you see anything?
- If you open the console (Inspect element > Console), do you see any errors in All notes?
- You used the add-on before the 3.7.2?
- (if true the previous) the previous release worked?
- You can see correctly notes via popup?

Thanks!

**Comment by bege10** [comment]
> @bege10 this shouldn't be the correct behaviour. Some other information needed:
> 
>     * If you press on "Export" can you see anything?
>     * If you open the console (Inspect element > Console), do you see any errors in All notes?
>     * You used the add-on before the 3.7.2?
>     * (if true the previous) the previous release worked?
>     * You can see correctly notes via popup?

- As written above, no reaction of the buttons (except getting bigger on click)
- None but this one which is correct AFAIK: 16:40:19.232 E1: Error: Missing host permission for the tab
in https://addons.mozilla.org/de/firefox/addon/websites-notes/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org 3 background.js:494:21
    closeStickyNotes moz-extension://c1a9b102-f67c-43bb-83c7-c6f4958e5070/js/background.js:494
- I didn't open the all notes page for a long time. I restored to 3.5 and it has the same issue
- Yes, as written in my OP notes are displayed via popup.

Uninstalling, restart Firefox, reinstalling doesn't help.

**Comment by Sav22999** [comment]
@bege10 ok, probably it's just an issue with showing "all notes" page, but it's very weird. Noone else reported me this issue.
I'll try to check something.

In case, are you available to try beta/alpha version (via debug)?

**Comment by bege10** [comment]
> In case, are you available to try beta/alpha version (via debug)?

Does that require a different Firefox version than the stable release? If so, I cannot help with beta/alpha version. I just had an eye surgery and must not spend much time at the screen. If it is possible with stable release, tell me how.

**Comment by Sav22999** [comment]
@bege10 sure, you can test with stable version, but this could cause problem either way current notes, so better not cause issues 😉

**Comment by bege10** [comment]
> this could cause problem either way current notes

That's not an issue, I can restore the notes.

**Comment by Sav22999** [comment]
@bege10 just release the 3.7.4 in which I have added some new console.error messages, so if there are errors during loading in All notes, it should be shown in the Console. Please, can you tell me if you can see anything?

**Comment by bege10** [comment]
Hi, v3.7.7 has the same issue, no information on the console.

**Comment by Sav22999** [comment]
@bege10 Ok, this is very weird so 🤔 

I put many console.error to each part where are generated buttons and notes, and if you don't see anything there is something of wrong.
Do you have any extensions installed? Maybe an adblock or something else blocks the generations in that page?
Can you try to use a "temporarily Troubleshoot mode" of Firefox and enable **only** Notefox please? https://support.mozilla.org/en-US/kb/troubleshoot-and-diagnose-firefox-problems#w_3-restart-firefox-in-troubleshoot-mode

**Comment by bege10** [comment]
I understand that this is weird. An error without any error notice.
I cannot activate an add-on in troubleshoot mode but I already installed Notefox in a new profile https://github.com/Sav22999/websites-notes/issues/58#issuecomment-1763414525
Even there the issue exists.

**Comment by Sav22999** [comment]
@bege10 Ok, try to use Notefox in another profile "by zero" (so, do not import your notes, just try to use the addon in a website and go in the All notes page to see what happens). Thanks!

**Comment by bege10** [comment]
> @bege10 Ok, try to use Notefox in another profile "by zero" (so, do not import your notes, just try to use the addon in a website and go in the All notes page to see what happens). Thanks!

That's what I did.

**Comment by bege10** [comment]
This path does not seem to come to a solution. As just said, what makes the difference between the last working and the first not working version?

**Comment by Sav22999** [comment]
@bege10 Actually from the two versions basically shouldn't be changed anything in All notes

**Comment by Sav22999** [comment]
@bege10 Can you send me the JSON of your Settings configuration?

**Comment by bege10** [comment]
Do you mean the JSON when exporting data? I don't have one, I would restore the notes manually. Currently there are no notes stored. The notice that there are no notes is missing in the all notes page and the buttons do nothing.
In the settings page I can change the settings but the buttons at the top of the page do nothing also. Here is the screenhot.
![Screenshot_343](https://github.com/Sav22999/websites-notes/assets/1184237/99f4e778-e5ab-41eb-b05f-0dd288fc9574)

**Comment by Sav22999** [comment]
@bege10 Ok, it looks like the JS scripts don't run in your browser. Because, if both Settings and All notes don't work... I think that it 🤔 

What Firefox version do you use?

**Comment by bege10** [comment]
See above:
Firefox 118.0.2 64-bit, German locale
Windows 10 Professional 64 bit

**Comment by Sav22999** [comment]
Ok, let me try another thing.
Go to "All notes" page. Open "Console" of that page and write "loaded()" manually (which is the function called when the page loads). Let me update about this please.

<img width="1512" alt="image" src="https://github.com/Sav22999/websites-notes/assets/32335378/88801720-c0fe-4573-ab50-219670a8dbeb">

**Comment by bege10** [comment]
14:29:45.557 Uncaught ReferenceError: loaded is not defined
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:299
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:209
    evaluateJS resource://devtools/server/actors/webconsole.js:949
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:846
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
debugger eval code:1:1
    <anonym> debugger eval code:1

**Comment by Sav22999** [comment]
@bege10 Ok, basically your add-on doesn't load scripts 🤔 

You installed via Firefox Addons or via file?

**Comment by bege10** [comment]
via AMO. The github files cannot be installed (not verified).

**Comment by Sav22999** [comment]
Ok. Don't you have any problems with other extensions, right?

This looks like an issue in Firefox, but I can wrong. I'll investigate. Thank you very much for your detailed information

**Comment by bege10** [comment]
Seems like the error I posted was because of the wrong page in the browser tools.
When I choose the address of the all notes page then I get this error:
`14:35:00.678 Uncaught ReferenceError: can't access lexical declaration 'sync_local' before initialization
    checkSyncLocal moz-extension://5d7935c4-5a1b-4adc-a91e-38052b46a0a8/js/all-notes.js:32
    loaded moz-extension://5d7935c4-5a1b-4adc-a91e-38052b46a0a8/js/all-notes.js:44
    <anonymous> debugger eval code:1
debugger eval code:32:5
`

**Comment by bege10** [comment]
Still the same. The console shows this error
`15:04:22.703 Uncaught TypeError: all_strings is undefined
    <anonymous> moz-extension://5d7935c4-5a1b-4adc-a91e-38052b46a0a8/js/all-notes.js:10
all-notes.js:10:5
    <anonym> moz-extension://5d7935c4-5a1b-4adc-a91e-38052b46a0a8/js/all-notes.js:10
`

I may not be able to continue today. Thanks for your endurance.

**Comment by Sav22999** [comment]
@bege10 Ok, this is a problem which I don't know how to fix, actually 😢 

You could try to ask in Mozilla Firefox forum, because the add-on doesn't load neither "background" script 🤷🏻‍♂️ Sorry so much

**Comment by bege10** [comment]
Do you use any functionality in v3.3+ and not in v3.2. that is not common to other add-ons? As far as I can see you added the general notes tab. I have quite a bunch of add-ons that work without issues.

**Comment by Sav22999** [comment]
@bege10 The problem is that your browser (and I don't know why) doesn't load script when you open in a new tab. Instead, if you open directly via popup, it works correctly

**Comment by Sav22999** [comment]
@bege10 sync_local is a variable declared in the scripts and it gets if it's "local" or "sync". By default it's local

**Comment by bege10** [comment]
That's the difference between the working and the not working version.

**Comment by Cade66** [comment]
@bege10 what is really odd it that your issue persists within a new profile, so the culprit cannot be related an about:config setting which would have been modified nor to an incompatibility with another extension.
I guess there is nothing in your environment which modifies your Firefox default settings and prefs, in particular no Autoconfig, no Group Policies, correct?

So we have:

1. Firefox 118.0.2 64-bit / Windows 10 Professional 64 bit
2. Notefox v3.2.1.1 is the last version that works. v3.3.1.8 is the first version with this issue.
3. Issue persists in new profile

Notefox 3.3 introduced:

1.  Now it's used "sync" instead of "local", so data should be sync with Firefox Accounts!
2.  Implemented function which converts local to sync

As it seems the problem could be related to "sync". But that shouldn't be a problem to start with, especially that the issue persists in a new profile.
My comment doesn't help, just trying to summarize. Gosh, this is definitely weird.
When you opened the new profile as you mentioned it, you installed Notefox 3.3 and nothing else.
You then imported your notes, I guess.
Rather than importing your notes, had you tried creating a new note instead to see if it appears in the 'All Notes' page?
I'm keeping your issue in mind, if I get up with anything I'll popin.

**Comment by bege10** [comment]
@Cade66 Thank you for your thoughts. They triggered own thoughts that led to a solution.
To your question: I hadn't even imported notes because even the buttons on the "All Notes" page didn't work.

I have prepared Firefox in [this ](https://github.com/Endor8/userChrome.js#einleitung)way to be able to run custom scripts. The scripts are not in a new profile, but the files in the installation folder are still there, of course. While reading your comment I remembered that this might be a reason why Notefox didn't work even in a new profile. I remove these files and alas - Notefox worked again.
Then I restored the files in the installation folder and activated the scripts in the profile one by one. And after all scripts where activated and running Notefox still worked - even after a few more days of testing. The preparation and the scripts never caused any incompatibility before and obviously don't do it now. So the issue is gone but it is still weird.
Thank you, also to @Sav22999 .

**Comment by Cade66** [comment]
@bege10 , I'm glad you found the culprit and the solution.
I use userChromeJS scripts as well here on Firefox, but I had installed the 'protocol' as proposed by [xiaoxiaoflood](https://github.com/xiaoxiaoflood/firefox-scripts) and my userChromeJS scripts are all in my profile's Firefox/chrome folder. What is essential of course is the content of userChromeJS' config.js file (or whatever other name it's been set to) in Firefox's install folder. New versions of Firefox may require an update of userChromeJS 'protocol' (emphasizing on the config.js file) : The xiaoxiaoflood installation has last been updated for Firefox ver. 111, still works flawlessly here on Firefox 115.4.0 ESR but not sure it does or will continue to on newer versions of Firefox. Wait and see, that'll be late 2024 for FF115+ ESR. Another point is that the protocol itself may be functional but some scripts may no longer be.

Whatever, glad you got the issue fixed.
