### ISSUE TITLE
High CPU usage when have the protected tabs on Firefox

### ISSUE THREAD

**Issue by Tykveg** [Sav22999/websites-notes#69]
Firefox 119.0 (64-bit) from snap, ubuntu
Website Notes 3.7.12 from Firefox add-ons store
After the update, if I have any tabs that are protected by Firefox (e.g. about:addons), for some reason the extension consumes a lot of cpu power (100% usage basically) (got it from about:processes and system monitor). If I close those tabs, everything is back to normal. Of course, if the extension is disabled, everything is fine (even if I have those protected tabs), so I'm certain that this extension causes it (I can't see what extension does 100% cpu usage in about:processes).

**Comment by Sav22999** [comment]
@Tykveg So you have this problem only on "about:addons" tab?

Have you tried on "about:debug", "about:blank", etc.?

Can you try also on "addons.mozilla.org".

Thanks!

**Comment by Sav22999** [comment]
Ok, this is very weird.
I thought there was some cpu usage for "unsupported" webpages, but it isn't.

I'll investigate right now, thank you very much and sorry for the inconvenience!

**Comment by Tykveg** [comment]
Also everything is fine when I open special extension pages, that starts with "moz-extension://"

**Comment by Sav22999** [comment]
@Tykveg  Ok, I think I've found the issue. I'll release an update in (max) an half and hour. Please, then let me know if there is yet this abnormal usage of CPU.

**Comment by Tykveg** [comment]
Okay. Thank you!

**Comment by Tykveg** [comment]
I tested beta branch. I don't see 100% cpu usage anymore with those tabs.

**Comment by Sav22999** [comment]
@Tykveg Perfect! Thank you. I'm releasing also on Firefox Addons, so in some minutes it should arrive officially via AMO 😄
