### ISSUE TITLE
When global notes are stored the toolbar button is always green

### ISSUE THREAD

**Issue by bege10** [Sav22999/websites-notes#72]
Hello,
as said in the topic: When Notefox contains global notes the toolbar button is always green. This is not helpful because one cannot see whether domain or page notes are available.
I don't think that the button needs to show the presence of global notes. The user should know that there are global notes.
However, to see that a domain or page note is available is important.

**Comment by Sav22999** [comment]
@bege10 this is the correct behaviour. The button is green when it's saved at least one type of notes 🤷‍♂️

I can add an option which permits to "manage" in some way this in Settings, so you can change the default behaviour, what do you think?

**Comment by bege10** [comment]
@Sav22999 If I am correct in earlier versions the toolbar button turned green when at least one **matching** type of notes was saved. I don't find that setting any more. Without that the color of the toolbar button says nothing any more.
I think the color should only change if there is a matching domain or page note.
If you want to keep it the way it is I will be very grateful for an option to change the behavior of the toolbar button.
Thank you in advance.

**Comment by Sav22999** [comment]
@bege10 There wasn't an option for that actually, but I can create it in the next release 😄 .

Thanks for the suggestion!

**Comment by Sav22999** [comment]
@bege10 I've implemented the new feature 😄 (but I'm working to some other improvements, so the update should arrive later

**Comment by Sav22999** [comment]
@bege10 Implemented in 3.9.1 😄

**Comment by bege10** [comment]
@Sav22999 This is really amazing! Settings for the green button for every circumstance and if set to open with page the notes popup opens with the respective tab: If there is no domain or page not it opens with global, if there is no page but domain note it opens with domain and if there is a page not it opens with that tab. I am honestly impressed. Thank you very much! Definitely worth a donation.

**Comment by Sav22999** [comment]
@bege10 Thank you very much, this is also thanks yo your feedbacks! ❤️
