### ISSUE TITLE
Некорректное поведение курсора при переводе строки

### ISSUE THREAD

**Issue by serg78ant** [Sav22999/websites-notes#74]
При вводе текста в заметке и нажатии перевода строки (Enter) происходит перевод строки и моментальное возвращение курсора в исходное положение - как будто были последовательно нажаты две клавиши "Enter" и "Стрелка влево (<-)".

**Comment by Sav22999** [comment]
@serg78ant Bug known with no fid currently. Actually, if you press Enter, although the cursor is shown to the previous row, you can start to write (without use arrow to navigate) and the text should start to write exactly from the correct position. Let me know

**Comment by serg78ant** [comment]
Unfortunately, he does not write from the correct situation. I press the input, the cursor remains in its place (do not follow the translation of the line), I start to enter the text and it is also entered on the cursor site, and not where it should be.

**Comment by Sav22999** [comment]
@serg78ant Ok.
I guess you inserted some text formatting when you get this issue, right?

**Comment by serg78ant** [comment]
Oh, no. This behavior of the cursor does not depend on the presence/absence of formatting. At the same time, not only the insertion of the line ("Enter") is made incorrectly, but also deletion: if you make several line transfers, then when you delete any of them, the cursor jumps to the top position. For example:
There is a text consisting of 10 characters.
We make (for example) 4 transfer lines, while, I remind you, the cursor is at the position of the end of the first line (since it itself returns here after each line translation).
I bet the cursor (for example, arrow keys) on the last (i.e. on 5) line - the cursor is now in the position of the beginning of the 5th line.
I delete ("Backspace") the line translation, but the cursor moves not on the 4th line, but jumps at the end of 1 line.

**Comment by Sav22999** [comment]
@serg78ant Please, can you record a video of this bug? I cannot replicated it on my side 😢 
Thanks for your help!

**Comment by serg78ant** [comment]
https://disk.yandex.ru/i/DkZPVNjX0wqeSQ

**Comment by Sav22999** [comment]
@serg78ant Thanks!
So, basically, as I can see the popup ignore totally the <br> tag 🤔 

So weird, in my browsers this doesn't happen.

I'll investigate, thanks!

**Comment by Sav22999** [comment]
@serg78ant I've found the problem, and I think I've fixed it.
I'm releasing the 3.9.1.1 release with this fix, update on Firefox Addons 😄
