### ISSUE TITLE
Иконка не всегда отражает правильный статус наличия заметки

### ISSUE THREAD

**Issue by serg78ant** [Sav22999/websites-notes#75]
Иногда заметка на странице существует, а индикатор (иконка расширения) не показывает этого - красный цвет. А иногда показывает - зеленого цвета. Поэтому приходится всегда, даже когда красного цвета, нажимать на иконку и проверять есть ли заметка на этой странице. Вот пример, текст заметки уже был введен и даже страница обновлена, а индикатор не изменяет цвет на зеленый.
![изображение](https://github.com/Sav22999/websites-notes/assets/34590996/78fd260f-8c82-4694-8263-b1566d3594a8)

**Comment by Sav22999** [comment]
@serg78ant Hi, thanks for reporting.

Update the addon to the latest release, and please, write in English

**Comment by serg78ant** [comment]
Thank you. I have no idea why it worked incorrectly yesterday. It's working well today. Thank you.
