### ISSUE TITLE
Notefox 3.9.2 : popup does not respect settings set to disable Advanced managing of urls (save notes per "sub-domains")

### ISSUE THREAD

**Issue by Cade66** [Sav22999/websites-notes#79]
Hi,

Just updated Notefox 3.9.1.3 to 3.9.2

Facing 1 issue and 1 oddity.

**_- Issue:_**
```
Notefox 3.9.2 / Settings /
Advanced managing of urls
When enabled you can save notes also per "sub-domains"
```
Though set to 'NO' in Settings appears nevertheless in the popup
Cannot manage to fix this via CSS, best I can do leads to the three-dot tab in the popup replaced by an empty space.

**_- Oddity_ (IMO):**

Notefox 3.9.2 xpi weighs 15.47 MB compared to 963.39 KB of ver. 3.9.1.3 because of a 23.7MB 'screenshots' folder.
I linger to understand the pertinence of adding these screenshots which are of course never used by the code and may be of any interest only for those who'd open the xpi to have a look at them. Takes space which is always bothering for Firefox profiles installed on a RAMdisk but even without such considerations seems IMO total nonsense.

Thanks for your work. I use Notefox extensively which is why I take the liberty of being straightforward :)

**Comment by Sav22999** [comment]
@Cade66 Hi, thanks for the reporting. I've probably wrong to compress the folder and I've added also screenshots 🤦🏻‍♂️, sorry

About the option in Settings, I'll investigate. Before the updating it worked correctly?

**Comment by Cade66** [comment]
@sav

> About the option in Settings, I'll investigate. Before the updating it worked correctly?

Yes, referring to previous Notefox 3.9.1.3

Concerning the screenshots, this is of course not an issue, only - IMO - a challenge in terms of pertinence.
Also, in my viewpoint, users, (some/many?) may consider an extension's weight and conclude when noticing that is is substantial (15MB?!) that it may be "complicated" so to say when in fact it is not but only due to the fact the xpi includes data which will not be used by the extension, mainly screenshots. I've seen this with other extensions, never understood why the developer had proceeded this way. Basic psychology and relevant that our minds may lead us to wrong conclusions. Of course there are users who don't care, look at an extension's weight. To make it short : the argument is really secondary :)

**Comment by Cade66** [comment]
Notefox 3.9.2.1 fixed the issue. Thanks!

**Comment by Sav22999** [comment]
@Cade66 Thanks to you!
