### ISSUE TITLE
Feat request: cloud saving for notes

### ISSUE THREAD

**Issue by Doomwhite** [Sav22999/websites-notes#82]
Saving the notes/settings in google drive/one drive/other clouds would be great!
Specially when using more than one computer.

**Comment by Sav22999** [comment]
@Doomwhite Great suggestion, but this implies the adding of external services (Google and Microsoft). It would be better if Mozilla/Google/Microsoft adds the support with unlimited storage using the "sync" feature

**Comment by Sav22999** [comment]
@Doomwhite I'm working on this feature 😄 
In the Notefox v4.0 will arrive the sync of notes!
