### ISSUE TITLE
Feature request: Domain independent from http / https

### ISSUE THREAD

**Issue by Fullmono** [Sav22999/websites-notes#86]
Repro step:

1. Go to http**s**://alkymia.be/
2. Add a note
3. Go to the equivalent http://alkymia.be/

> The note doesn't appear.

The domain notes should appear independently of http / https.

**Comment by Sav22999** [comment]
@Fullmono That's true, I'll release a fix asap.

Sorry for this inconvenience and thanks for the reporting!

**Comment by Sav22999** [comment]
I've implemented this feature in 3.10.1

You need to enable it (switching on "Yes") the checking with all supported protocols 😄 
Enjoy!
