### ISSUE TITLE
Global Notes not displaying

### ISSUE THREAD

**Issue by LhrApps** [Sav22999/websites-notes#88]
Hello, global notes are not working, I can add them, but they are not displayed in the addon menu, they only appear on the all notes display page.
And popup global not opening.

![image](https://github.com/Sav22999/websites-notes/assets/25826970/4ef1241f-d8d9-4ad9-8485-314c302a42ae)
![image](https://github.com/Sav22999/websites-notes/assets/25826970/ff493f80-63e0-47ac-9e21-fca46369ea80)

Firefox version: 123.0.1

**Comment by Sav22999** [comment]
I’m sorry about this inconvenience, I’ll check asap

Saverio

**Comment by Sav22999** [comment]
@LhrApps I'm working on this issue. I'll release asap a fix.

Sorry

**Comment by Sav22999** [comment]
Fixed in #89
