### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by bege10** [Sav22999/websites-notes#95]
Hi,
I changed the font to Open Sans but the notes remain in handwriting font. For me the handwriting is not as clear to read as a normal font.

**Comment by Sav22999** [comment]
@bege10 Hi, sorry for the inconvenience.
There is a bug, but in the next release it should be fixed.

I'm refreshing totally the UI and the UX, so the update should arrive in some days I hope.

In the meanwhile, if you need to see a note, you can try to paste it on the notepad. Sorry
